### ISSUE TITLE
Layout: GRC Webpage needs links like the orignal Java app page

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#10]
the oringal app web page has supplementary information on it, not just the app, like
instruction on how to use the app.

Seems important.

We should add those back

I put my copies of them in Javascripts/awt_java_source/www/, but these are not_GOLD_
John Wieczorek hass the final word on this.
from the original webpage, sans format, (http://manisnet.org/gci2.html)

Calculator Manual (English)

Georeferencing Guidelines (English)

This application was written by John Wieczorek with contributions from Qinghua Guo, Carmen Boureau, and Craig Wieczorek.
Interface translations provided by: 
Gustavo Iglesias (Español), Jose (Wly) Dos Santos (Português), Tendro Ramaharitra (Français), Robert Hijmans (Nederlands), Peter Desmet (Nederlands)

John Wieczorek 3 Nov 2001

Rev. 6 Feb 2013, JRW
University of California, Berkeley, CA 94720, Copyright © 2001-2013, The Regents of the University of California.

 Creative Commons License 
This work is licensed under a Creative Commons Attribution-Share Alike 3.0 License.

**Comment by tucotuco** [comment]
Yes, we want all of this stuff, but it will have to be amended. Specifically, the following need to be substituted for the original:

Change to: 
"This application was adapted from an earlier version in Java by John Wieczorek with contributions from Qinghua Guo, Carmen Boureau, and Craig Wieczorek."

Add: "Georeferencing Quick Reference Guide" at http://manisnet.org/GeoreferencingQuickReferenceGuide.pdf.

Add:
"Wieczorek et al., 2004. Point-radius method for georeferencing locality descriptions and calculating associated uncertainty. International Journal of Geographical Information Science 18(8):745-767." at http://manisnet.org/Wieczoreketal2004PointRadius.pdf.

Change to: 
"Rev. 18 Nov 2015"

Change to: 
"University of California, Berkeley, CA 94720, Copyright © 2001-2015, The Regents of the University of California."

Remove:
"Creative Commons License 
This work is licensed under a Creative Commons Attribution-Share Alike 3.0 License."

Add: 
<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Georeferencing Calculator</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.<br />Based on a work at <a xmlns:dct="http://purl.org/dc/terms/" href="https://github.com/VertNet/georefcalculator" rel="dct:source">https://github.com/VertNet/georefcalculator</a>.

**Comment by ElSkunkito** [comment]
all added and fixed.
NOTE!!!
I used absolute links to manisnet.org, not relative links, which seems bad.
very torn
should we add the manisnet.org links into source abnd user relative links???

commit c032989..9d5eb17 "added related links"

**Comment by tucotuco** [comment]
Absolute links will be needed. The calculator should be downloadable and runnable from a local install.

**Comment by ElSkunkito** [comment]
all links absolute and tested. closing.

**Comment by ElSkunkito** [comment]
re-opened, assigning JRW

una punta o dos de clarificación

links to js are files are realtive, not absolute
all other links are absolute

as is, if a person has a local copy of the GRC, and all its associated .js files
and they are not connected to the internet
the links at the bottom, the manual and what not will not work.

if they do not have the app local, but work from a website, all links and app will work.

tsok?

**Comment by tucotuco** [comment]
Hmm, making me think that we package all together. Let's have a docs folder with the linked information in it and relative links.

**Comment by ElSkunkito** [comment]
I added the contents of the 3 main links.

should file a seperate bug for packaging.issues

for ex
javascripts should be renamed to source
awt refernce files moved to georef level rather than source, and so, filing.

opened issue #70 for that purpose

realtive put bac in, fixed by commit fc95a7f..e5e7439 "added guides n manuals"

close?

**Comment by ElSkunkito** [comment]
i sould add the 3 main docs are under
\georefcalculator\javascripts\docs
grabbed from
http://manisnet.org/gci2.html

**Comment by tucotuco** [comment]
Closing this one in favor of Issue #70.
