### ISSUE TITLE
Layout: Copyright legal / text problem

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#11]
From grc.html, the copy right text is 
   Copyright 2015 Regents of the University of California
Should it be
    Copyright(c) 2015 Regents of the University of California
note the added(c), no space.
Seems like a dumb question, but when it comes to legal I know 0 so it is best to file a bug.

search grc.html for Copyright to fix it, if needed.

**Comment by tucotuco** [comment]
Copyright 2015 Regents of the University of California is complete and sufficient. No change there.
