### ISSUE TITLE
BUG: Default Coordinate System not set to 'decimal degrees'

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#14]
I am fairly sure the default Coordinate system is supposed to be Decimal Degrees.
It is not, its set to 'derees minutes seconds', or somehow the defaul is getting changed.

affected control: ChoiceCoordSystem
this also affected the display of DMS, DD and DDM controls. DD controls should be display,
but DMS controls are instead because ?DMS set at the default?

Repro Steps:
  reload the page
  choose calc type                              coords and error...
  choose locality type(ChoiceModel)  Distance along orthoga...

  Look at controls under 'Coordinate System'

```
Actual Results:
    Degrees Minutes Seconds controls are shown

Expected Results:
    Decimal Degrees controls are shown.
```

**Comment by ElSkunkito** [comment]
do we care???

id decimal degrees the most comon type?
if so I will make it the default. pretty easy rly.

**Comment by tucotuco** [comment]
Decimal degrees is probably the most common as people pull coordinates from Google Maps and the like (see issue #1 ). It is also a lot cleaner on the UI and easier on new users to have fewer controls.

**Comment by ElSkunkito** [comment]
back at you for executive desicion.

I can change the ordering in the SELECT box
from
DMS
DD
DDM
to alpabetical order(en inglais)
DD
DDM
DMS

it passes all tests fine.
it makes DD the default
canonical is maintained by other methods than order in text box.

other methods of defulting to DD did not work.

**Comment by ElSkunkito** [comment]
note as of 11/24 21:30 github has the experimental ordering that fixe the issue.

**Comment by tucotuco** [comment]
Fix is satisfactory.
