### ISSUE TITLE
BUG: Changing language improperly resets Step One....

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#2]
... and Two controls to empty when in step 3(and possibly step 2)

Repro Steps:

ReLoad the page
Choose an language
Choose a CalcType
Choose a Locality( aka Model on the code level )
   Note everything is in the proper language
choose a different language
Expected Results
   Chosen CalcType and Locality Type _currently_ chosen options get rewritten in the newly selected language and he se;ected option stays selected

Actual Results
   Chosen calctype gets selected set to Empty ""
   Chosen Loc ype(Model) gets selected set to Empty ""

Severity:
   unknown, probably pretty bad

**Comment by tucotuco** [comment]
I think this behavior is OK. If someone changes the language partway through, they can expect to have to start over.

**Comment by ElSkunkito** [comment]
the problem is none of the other controls gets hidden.

I too would expect if you switch from lang A to B its a clean do over
values and choices lost,
steps 2 and 3 controls disappear
ChoiceCalcType gets set to Empty ""
ChoiceModel(loca type) gets set to Empty "", but not visible.
LabelStepOne  gets uiShowElement
LabelStepTitle  gets uiHideElement

**Comment by tucotuco** [comment]
I would not lose "memory" of the choices for the coordinates and other such selections. For now, clean is fine. But memory of those numbers avoids time-consuming entering.

**Comment by ElSkunkito** [comment]
luckily the number are not lost on language change.

I am unsure if this is a bug anymore, please advise

**Comment by ElSkunkito** [comment]
correction, the java app doest NOT leave them empty, it changes language, and all controls remain visible, translated. will fix.

**Comment by ElSkunkito** [comment]
I seem to have fixed this, and other language switching issues.
