### ISSUE TITLE
BUG: Java vs js var vs int, double promotion/ type conversion

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#21]
When converting Java to js the rules for int promotion to double, or visa versa  was not dealt with.

ex 
int i = 5
double d = 3.1415926;
double z = d \* 5
int z = (double)i /  3;

This could introduce bugs.

Audit?
I dont know exactly how to deal with this.
Check java source for type conversion and make sure js vars act the same exact way.

**Comment by ElSkunkito** [comment]
I have yet to notice an issue.

auto test #6 MAY be manifesting rounding differences, but not for the stated reason.

Global doubles do not get rounded, we work on the rounded number produced from it
If the original dobule gets changed in value the next rounding wll be from a full double, not from the rounded double result from before

I think this is the way the Java app works anyway though.

**Comment by ElSkunkito** [comment]
my previous statement is incorrect. there have been issues, but not in precision.
In addition when using strings.

c= a + b
or a+= b
if a is "1.0"
and b is ".1"
the c is "1.0.1"

I deal with these situations via parseFloat( a ) + parseFloat( b )

**Comment by tucotuco** [comment]
Does that mean this issue can be closed? Calculations do seem correct.

**Comment by ElSkunkito** [comment]
closing. something to always be aware of though.
