### ISSUE TITLE
House Keeping: Rename some files

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#25]
RENAME
/javascripts/
grc2.css to <a better name>.css
test1.js to <a better name>.js reflecting it contains mostly logic/calc funtions
lowercase Datumerror.js
gc.ui.js <a better name>.js reflecting it contains mostly ui logic

**Comment by ElSkunkito** [comment]
JRW consider for release milestone

low risk, fast.

**Comment by tucotuco** [comment]
Agreed. Make it so.

**Comment by ElSkunkito** [comment]
commit e5e7439..9d631bc "file renames"

[master 9d631bc] file renames
 5 files changed, 6604 insertions(+), 6606 deletions(-)
 rename javascripts/{grc2.css => grc.css} (100%)
 rename javascripts/{gc.ui.js => grc_ui.js} (96%)
 mode change 100755 => 100644
 rename javascripts/{georefcalculator.js => properties.js} (97%)
 mode change 100755 => 100644
 rename javascripts/{test1.js => support.js} (97%)
 mode change 100755 => 100644

**Comment by ElSkunkito** [comment]
re-open and assigning  JRW

i left the main webpage named grc.html
not only is the an incorrect abbreviation, it doesn't match the original odd name of gci2.html.

what should main page's name be?

**Comment by tucotuco** [comment]
Keep the main web page as gci2.html.

**Comment by ElSkunkito** [comment]
grc.html renamed to gci2.html
grc.css  renamed to gci.html
grc_ui.js  renamed to gci_ui.js

commit 48c5cfc..51530ca

is this closable now?

**Comment by tucotuco** [comment]
Renaming is fine. Encoding was messed up in download, methinks. I'll fix it and change the crazy folders "Georeferencing Calculator Manual v2_files" and "MaNIS HerpNet ORNIS Georeferencing Guidelines_files" to "images".

**Comment by ElSkunkito** [comment]
hmm, dl direct from github shows fine pics.

the img link no longer work because of the locations

&gt;img src="./MaNIS HerpNet ORNIS Georeferencing Guidelines_files/datumerror.jpg" width="90%"&lt;

note that the help pages expect the images to be UP in ./docs/MaNIS HerpNet ORNIS Georeferencing Guidelines_files/ and ./docs/Georeferencing Calculator Manual v2_files/

where they currently the live in
../docs/*

**Comment by tucotuco** [comment]
Fix for Georeferencing Guidelines document in commit c825b604b703c81416e420fe3df5c0b776ee296d.

**Comment by tucotuco** [comment]
Fix for Georeferencing Manual in commit a7fae08351391004a45eaa9f8bceb70e9a5e396d.
