### ISSUE TITLE
BUG, Feature: Add number formats, w/ localization

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#3]
Some Decimal numbers need formatting
Max value, precision max.

In addition it would be nice to add back in localization, the choices from original
being English and French.  1000 vs 1,000

**Comment by tucotuco** [comment]
It is important that the precision of the coordinates keep seven digits of precision to the right of the decimal in display and calculations. This is to be able to preserve the exact same coordinates as displayed after transformations back and forth among all coordinate systems.

**Comment by ElSkunkito** [comment]
search for Intl.NumberFormat on google, I beleive this tackles half or more of the problem.

**Comment by ElSkunkito** [comment]
I have added back in "half" of the formatters, where we check precision of the numbers.
I have not added back checking the values we are grabbing from format test boxes, where . and , may come intio play.

I will add that as its own bug as it's less important than "this half"
