### ISSUE TITLE
Update links to GeorefCalculator

### ISSUE THREAD

**Issue by tucotuco** [VertNet/georefcalculator#36]
Seek out everywhere the Georeferencing Calculator is referenced and get the links updated.

manisnet.org
herpnet.org
georeferencing.org

**Comment by dbloom** [comment]
https://www.idigbio.org/wiki/index.php/Category:Georeferencing_calculator  (Appliance)
https://www.idigbio.org/wiki/index.php/Georeferencing#Georeferencing_Calculator
http://users.wfu.edu/garck8/GIS%20Links/GeorefResources.htm - may update if HerpNET updates.

We should also send a notification to listerservs such as NHCOLL.

**Comment by tucotuco** [comment]
Yes, once there is a Calculator tried and true.

**Comment by laurarussell** [comment]
http://georeferencing.org/tools.html

Also, here is a google search to see what other places/docs might have the old link.  https://www.google.com/?gws_rd=ssl#q=manisnet.org%2Fgci2.html

**Comment by dbloom** [comment]
Let's just send a copy to Google.  That should cover all the bases.

**Comment by tucotuco** [comment]
Also need to update the page at http://manisnet.org/search.shtml

**Comment by tucotuco** [comment]
Updated the MaNIS site and the links within the corpus of the calculator and its documents.. The location of the Calculator remains the same as before, so no updates for that need to be made.  Other maintenance mentioned in this issue should be in separate issues.
