### ISSUE TITLE
BUG: ???? Scale and distance converter controls are always visible

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#38]
The original java source has them inivisiable until step 3.

Do we care?

Is there a bug if we dont, perhaps language or layout?

**Comment by ElSkunkito** [comment]
probably have to use ui Show/Hide Element???

**Comment by tucotuco** [comment]
Executive decision. The converters can be there and fully functional always.

**Comment by ElSkunkito** [comment]
changed title, purpose of bug per exec descision

**Comment by ElSkunkito** [comment]
Fixed, also fixed up the layout somewhat
