### ISSUE TITLE
BUG: formatters, we do not check input for Local

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#45]
note, we DO check precision now, like the JAVA app does.

However we do ot format input from ENGLISH to Local.FRENCH.

, for . and such.

**Comment by ElSkunkito** [comment]
see also ( closed) issue #3 for relevant commentary.

**Comment by tucotuco** [comment]
Holding on decision until all other high priority issues are closed. At that point, we'll have to decide if this release will support , as a decimal separator at all. If not, the language properties that use , (e.g., "0,01 grados") will have to be changed.

**Comment by tucotuco** [comment]
Will no longer support Locale settings. All numbers will have . as the decimal and no thousands separators. Changed properties to match this decision in 1bdea5da7ea984466012753f88755972a3e4698c.
