### ISSUE TITLE
Layout: Alignment of offset controls is ++ungood and other issues

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#5]
Changing scope/purpose of issue, see after repro steps, actual, expected

Repro steps
   reload page
   leave language as "English(local)"
   choose CalcType Coordinates and error
   choose LocalType(ChoiceModel in code) Distance along orthogonal

   note the positions of
       North or South Offset Distance
       East or West Offset Distance
   and associated text controls. Pretty close to what we want

   switch to Espaneol, ignoring Issue#2 "Changing language improperly resets Step One..."

   Actual Results
      the position of controls TextFieldOffset and TextFieldOffsetEW move with size of
      text in LabelOffset and LabelOffsetEW

```
Expected Results
    left alignment and size of the controls stays constant, and aligned with
    "Extent of Named Place" and "Measurement error" controls
     LabelExtent, TextFiledExtent, LabelMeasurementError, TextFieldMeasurementError
```
# 

adding scope.
We either go with absolute x y  and size values for the UI, or use HTML resize capabilities.

Per discussion absolute XY is good for screen shots, documentatikon.
And the all important teaching newbs a complext ui.
Having elements shift in size and position.may be disconcerting.

However aboslute also has disadvantage, some obvious.
A less obvious one is it will take more time to complete than improving HTML layout.

And besides HTML layout has its own built in advantages over absolute.
Think people with poor eyesight, or with very high res monitors.

This issue is to give HTML layout a try. If it dfails to produce
pretty results we'll take on absolute.

**Comment by ElSkunkito** [comment]
passing to JRW for sugested improvements.

commit f56fd04..c2d3e6e   --"layout, 2 of ?"
"

Deved at 640x480, Chrome 39, windows 7,
all languages checked

**Comment by ElSkunkito** [comment]
beyond 640the layout starts to look bad again.
no specifics at the moment. i'll study it later.
genrics:
converter controls get wonky.
buttons are wonky.
things look 'weird'.

I already fixed, but not commited loc type

**Comment by ElSkunkito** [comment]
aside: when biggerized, increasing fint size make things look nice again.

still, we want to be lazy, 
the calc, prmote buttons must be next tgo each other for less mouse travel time.

yes. i am that lazy.

**Comment by tucotuco** [comment]
Looks mostly very good. 

Choice boxes on Mac need to be slightly wider than on PC to show string within. Note W in East or West Offset Distance, minutes in degrees decimal minutes, and km in Distance Unites and Distance Converter. However many pixels extra needed to show km, add that to all Choice boxes.

Calculate button can go right, splitting the difference to the Promote button to get it off the edge of the box to its left.

**Comment by ElSkunkito** [comment]
this is going to be tough.

the "km" and "N/S" "E/W" were very tough as is, no room for error.
--I tried one trick, please check if visible now.

minutes, in DDM/DMS,much more room for wiggle
--please try again

calc button
--intructions not followed, see if you like it.

other
--I added some cuteness for highlight current control to make it more obvious.

please try portuguese, its the worset for layout.

commit 7229f3d..905f0db   "layout 3 of ?"
commit 905f0db..c032989   "button calc spacing"

assigning to you for more suggests

**Comment by tucotuco** [comment]
All perfect.

**Comment by ElSkunkito** [comment]
and closing.
