### ISSUE TITLE
BUG, Layout: A clever method  for enabling debug mode is needed

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#50]
The final version to the end users should not have the buttong "Full Auto Testing!!!" or the SELECT fro run test 0-7 visible.

We need a clever way to make it visible on command.

**Comment by tucotuco** [comment]
I think it best not to have this enabled in the working App. Rather, make it as easy as uncommenting one line of code to enable it for debugging in development.

**Comment by tucotuco** [comment]
Important to remove the visibility of these controls before release. Making it easy to turn on is lower priority.

**Comment by ElSkunkito** [comment]
his is what I have done.

fat BUTTON and ChoiceTest SELECTare no longer present in HTML.
The java script source for testing is not present either.

if you press CTRL + ALT + SHIFT + d the java scripts will load
and "fat" and "ChoiceTest" will appear at the top of the page.

further pressing of CTRL + ALT + SHIFT + d
will hide / unhide fat and ChoiceTest

The only refernce to tesint is function downLoadTests() and it calling in BodyKeyUp

commit e40fc9d..6ec6a97

 Seem good?

**Comment by tucotuco** [comment]
Is good.
