### ISSUE TITLE
BUG: fix disappearing results on tab key

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#55]
when tab is pressed(key up) the results are cleared.

es no bueno.

fix it

search gc.ui.js for *KeyUp
that funtion is the source of the problem and easy place to fix it.

**Comment by tucotuco** [comment]
k, how bout this for results
(i filed a new bug on dissappearing)
on tabbing to results, all text is selected.
you can then just ctrl+c

or maybe tab to a button, "copy to clipboard"
or if you want to get fancy, add to new 'results pane'
results pane is a new text area that collects multiple results which you can select all out of.

basically, i'm lazy, I do not know whats happens to the results.
but I can magine ways to help ppl be lazier in post results gathering, processing.

**Comment by tucotuco** [comment]
Tab to results, all text already select, just need to CTRL-C or COMMAND-C.

**Comment by ElSkunkito** [comment]
done.
