### ISSUE TITLE
Request to pull external source

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#58]
https://github.com/madrobby/keymaster

MIT licence.

not sure how to deal with it...

I may not do this, its just a possibility unless its a hassle.

What do I have to do for external source?

**Comment by tucotuco** [comment]
No worries. Whatever gets used from that source just needs to be accompanied by the same rights statement.

"The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software."

**Comment by ElSkunkito** [comment]
Not needed at this time, closing
