### ISSUE TITLE
BUG put gazetteer back in and deal with any index issues

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#59]
replacing gazetteer with Google maps, while logic has follow on effects such as common terms
and documentation.

Put gzaette back, bit do not REPLACE google. just add it back and deal with any indexing issues
accordingly.

**Comment by ElSkunkito** [comment]
gazetteer has been ut back, and google maps added.
commit 4187af4..959fe29

**Comment by tucotuco** [comment]
However, tests 2, 3, 5, and 6 select Google Earth/Maps. These should select gazetteer.

**Comment by ElSkunkito** [comment]
fixed local.
