### ISSUE TITLE
Enchancement: format*.checkFormat() on focus lost for text controls

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#61]
this will have to be post release as it is probably not.. as easy as it seems.

We check formats of controls numbers for decimal max places and what not upon pressing Calculate

I was thinking while a final check is good, like we do now,
but we should also be checking formats, ie max decimal places, tru numbers min max values
when the text control is exited is even better.

**Comment by tucotuco** [comment]
Is there a question here? Please clarify.

**Comment by ElSkunkito** [comment]
apologies: a very poorly written issue on my part
I have edited the description to be hopefully more clear.

**Comment by tucotuco** [comment]
There should be no need to check the input for number of decimal places. Simple truncation to the needed length is sufficient.

**Comment by tucotuco** [comment]
No need to fix. Closing issue.
