### ISSUE TITLE
BUG: urchin tracker

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#64]
hidden at theend of the public java GRC is a tracking link

it is using a relative link.
do we want this link at all?
relative, or packaged with source

<script src="./Georeferencing Calculator_files/urchin.js" type="text/javascript">
</script>

<script type="text/javascript">
_uacct = "UA-386033-2";
urchinTracker();
</script>

**Comment by tucotuco** [comment]
I don't really care if there is a tracker anymore.

**Comment by ElSkunkito** [comment]
urchin tracker removed. no commit # at this time.
