### ISSUE TITLE
BUG: test* function(s) should show error dialog

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#65]
set calc and loc type
set 'coord system' to 'decimal degrees'
put 234 in Latitude(exceeding max value)
press calculate

Actual:
  nothing visdual to the user, no text results
  in the console there is the error text "ERROR: testParameterLimits() failed at testLatLongLimits"

Expected:
 error dialog with the offending control box highlighted and a relevant error message displayed

may be related to issue #60 

not sure if its a release milestone, but it is a bit of bad user experience.

**Comment by tucotuco** [comment]
I am seeing the error dialog on Chrome Mac OSX

**Comment by ElSkunkito** [comment]
whewww. non error.

earlier, due to a inifinite recursion bug I had to turn that partcular alert off.
reaload the page does not reset the recursion "dont show this alert" again.
Thats built into chrome.

open the page in a new tab fixes it.

closing.
