### ISSUE TITLE
BUG: heading, not nearest degree can cause frustrating user issue

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#66]
a real corner case

probably true of other controls that get hidden

best explaned by example

repro:
choose any calc type
choose loc type 'dist at'
choose direction 'nearest degree' if not already chosen
put "7a" in for TextFieldHeading, next to ChoiceDirection
chose calculate
look for error dialog
click ok
for choice direction, choose something other than 'nearest degree'
chose calculate

actual result:
  error dialog telling user to fix now hidden control TextFieldHeading

expected result:
  hidden data is not considered for error purposes

better result
  on bad input user is forced to correct it, or warned of set to 0

note: the original Java app is a lot more loose on parsing numbers.
7a auto becomes 7 with no error or warn
0.0.0 becomes 0.with no error or warn

**Comment by tucotuco** [comment]
Definitely better to not error on hidden controls. Good find.

**Comment by ElSkunkito** [comment]
fixing this must be done carefully considering javas loose parsing of numbers.
perhaps it used to be set to 0 on empty then used laterr, hidden or not.
0 effectively taking it out of consideration...

other possible issues.

**Comment by tucotuco** [comment]
The parameter is not supposed to be used in any calculation in which it is not visible. If it was, 0 would be the equivalent of N.

**Comment by tucotuco** [comment]
Fixed in 1ff4f3d8c1fc4448bd0fc58b8c8ffc3b7c59b2ed. Please confirm.

**Comment by tucotuco** [comment]
Confirming correct. Closing.
