### ISSUE TITLE
BUG: ??? highlighted error color is substandard

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#67]
when a text control is found to have bad data in it,
ex 193 when max value is 180,
an error dialog results, and the text highlighted in medium-sky-blue.

Originally I set errored number to red text, which is bad for the surprisingly large number of people that are RG color blind.

so I changed to medium-sky-blue.

medium-sky-blue.is _way too ugly and is too light_.
blue was.. not good either.

blue does not imply alarm, red does.
but red is bad...

change it to red-Orange, or other use some other background foreground tricks?

please advise.

**Comment by tucotuco** [comment]
How about BOLD red? Keeps the red for those who can benefit from it and adds bold as an indicator for those who cannot.

**Comment by ElSkunkito** [comment]
so let it be written, so let it be done.

i am no expert but i believe it will end up orange yellow bold for RG color blind. that's good contrast.
