### ISSUE TITLE
Layout, Bug, add semi absolute sizing

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#68]
from JRW

html laiyout looks bad at 'off sizes.'

rather than fight html to look good at every size all the time
there should be a key sequence, or button to up/down to known good sizes.
setting control widths, etc to predetermined sizes auto-magically

640, 800, 1280, maybe more

could take a few hours, or 6 days

**Comment by tucotuco** [comment]
Just one necessary, for 640x480. If you just set the frame size, doesn't the layout follow automatically, as when you resize the browser window?

**Comment by ElSkunkito** [comment]
not perfectly.
fonts remain small, some controls width fit the contained text for width.
for height, always the same if font is not changed, so it looks spacey and wierd when big.

hmm...
but I see what your saying...

tinking.

**Comment by ElSkunkito** [comment]
I'll meet you more than half way here.

app now defaults to 640.

want it bigger?
CTRL+ grows app proportionally, no fuss or mess.

commit 9d631bc..736c816  "absolute sizing++"

please advise if you want a larger default, other wize close with majestic heaven force.

**Comment by tucotuco** [comment]
Majestic. Closing with appropriate force.
