### ISSUE TITLE
BUG: packaged georef manual has bad links

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#69]
assigning JRW for consideration, pri, advisements.

production release?
high pririty bug?

from
georefcalculator/javascripts/docs/GeoreferencingCalculatorManualv2.html

It will be useful to run the calculator while reviewing this document; to do so, either download the stand-alone version of the calculator (http://manisnet.org/gci2.zip) or use the online version at http://manisnet.org/gci2.html. When the application is finished loading it should appear as in Figure 1, below.

also at bottom
ersion     Displayed in the bottom left-hand corner of the Calculator as yyyymmdd(language). Example: 20110430en = English version created April 27, 2011. The changes from version to version are given in a change log file.
John Wieczorek, 11 April 2002
Rev. 21 Jan 2006, JRW
Dave Bloom, John Wieczorek
Rev. 24 Apr 2011, DAB
John Wieczorek
Rev. 6 Feb 2013, JRW
University of California, Berkeley, CA 94720, Copyright © 2001-2013, The Regents of the University of California.

maybe others

**Comment by ElSkunkito** [comment]
grabbed manual from http://manisnet.org/gci2.html
put under georefcalculator\docs\

**Comment by tucotuco** [comment]
This is one of the places where there need to be updates as mentioned in Issue #36.

**Comment by tucotuco** [comment]
Fixed in commit a7fae08351391004a45eaa9f8bceb70e9a5e396d.
