### ISSUE TITLE
Add DMS, DDS controls into HTML

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#7]
there are are only DD contrlos

This is going to make the raw HTML ugly. :)
onLoad should fix it.
Liberal use of uiShow/HideElement will be needed as setVisibility controls still take space.
Show/Hide makes them .. dissapear from layout.

**Comment by tucotuco** [comment]
Could non-visible containers maintain layout under changes of selections?

**Comment by ElSkunkito** [comment]
using the setVisibility()\* function will make a control visible/inivisible, but take space.
This is normally what you want.

using the uiShow and HideElement functions remove the control from HTML layout consideration
The control exists, but take 0 layout space.
In the case of LabeStepZero("Step 1 visually") and LabelTitle("Georeferncing Calculator")
you only want 1 of them visibly AND taking space at a time.

This is also true for the DD,DMS, DDS controls as when used they occupy the same space.

_see issue 9 "ui_ functions naming has no convention"
