### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#70]
javascripts should be renamed to "source"

awt_java_source reference files moved to georefcalculator level rather than under "source"

**Comment by tucotuco** [comment]
Agree on renaming javascripts to source. Let's put awt_java_source in java_deprecated under source. Let's put docs at same level as source. If css will not be used, remove it.

**Comment by ElSkunkito** [comment]
awtBLAH became java_deprecated
commit 88ca53a..4389df7 "renaming directories"

docs moved
commit 4389df7..48c5cfc  "docs moved"
this will break links when running directly from github vertnet/georef or a local grab of git.
package will have to have docs hang off root directory.

.css is most required.
CSS is the lazy persons way of writing HTML

keeping open to collect more issues

**Comment by ElSkunkito** [comment]
it is poor form to recycle bugs. new bugs should be filed instead
closing.
