### ISSUE TITLE
Language change resets Coordinate system

### ISSUE THREAD

**Issue by tucotuco** [VertNet/georefcalculator#72]
From fresh start:
Choose Calc Type
Choose Loc Type

Coordinate  system is decimal degrees in English (local).

Change language to Nederlands

Coordinate system changes to graden decimale minuten while controls remain for decimal degrees.

This happens every time there is a language change - controls remain for previously chosen coordinate system, but coordinate system select goes to degrees decimal minutes equivalent.

**Comment by tucotuco** [comment]
Language change also resets datum select to datum not recorded equivalent.

**Comment by ElSkunkito** [comment]
dang, more controls are affected to...

this is going to take a few. I'll probably write a series of tests for it.

**Comment by ElSkunkito** [comment]
yes, this is going to take a few more hours.
the only way to test this realiable for all controls is better test framework.
70% done with it.

the bonus(i)?
language Independence testing
mildly lazier testcase writing
test re usability, extra lazy test case writing
test versatility

stop me if this is the wrong path for 11/29/15 PM.

**Comment by tucotuco** [comment]
It is a fine path. Pray continue.

**Comment by ElSkunkito** [comment]
with JRW finding other issues, quickly, I am continuing on the test framework that supports this bug
as it will be very useful for those issues as well.

**Comment by ElSkunkito** [comment]
not as a result of auto-tests.

I no longer get a repro on any dropdown list box..
Can you try again

**Comment by tucotuco** [comment]
Seems resolved. Closing.

**Comment by ElSkunkito** [comment]
the _kreepy_ thing is I didnt do anything to fix it, but I did see the bug in action.

In one of my fluries it must have been fixed by accident. hehehe. too much fun.
