### ISSUE TITLE
Packaging: java script can be squished for quicker online download

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#73]
in these times of phat pipes I'm not sure if it matters but...
there are utilities to take javascript source and remove all unneeded spaces, tabs, etc.

I do not recall the name(s) of them.

the biggest file is Datumerror.js, 800KB.
my guess is you get a 3-5% squish.

the rest of the files total ~150k. similar squish, or less.

It's not worth it in my opinion, but i'll just throw it out there for consideration.

**Comment by tucotuco** [comment]
http://jscompress.com/ compresses gci_ui.js by 29%, saving 28kb.  DatumError.js is compressed by 40%, saving 324kb. That's a better squish than expected, but I don't think the Calculator is big enough to matter. Also, I don't think we want to manage a dev readable version and a production compressed version. Especially given that users can install the whole thing locally, I would opt not to do this, though it is a good thought.
