### ISSUE TITLE
BUG: setting coordinate system does not preserve canonical coordinates

### ISSUE THREAD

**Issue by tucotuco** [VertNet/georefcalculator#74]
Select Calculation Type "Error Only"
Select Location Type "Distance only"
Select Coordinate System "degrees minutes seconds"
Enter Latitude 35d 22m 24s N
Enter Longitude 119d 1m 4s W
Select Coordinate System "decimal degrees"

Expected: Latitude 35.3733333 Longitude -119.0177778
Observed: Latitude 35 Longitude -119

Further observations: If Calculate is clicked before changing coordinate system to decimal degrees, Longitude is correct (-119.0177778), but Latitude is 35. The, if "degrees minutes seconds" is selected, the minutes and seconds in Longitude are also set to 0.

**Comment by ElSkunkito** [comment]
local copy, not much different than JRW
it's worse
i get
Observed: Latitude 35 Longitude -35

checked vs JAVA gci2.html, JRW expected are indeed correct.

**Comment by ElSkunkito** [comment]
fixed with commit 8b6c804..3f51ed7

In addition to the above issue, bug there was an issue where switching from DMS to decimal degrees, then back to DMS would zero out DMS minutes and seconds control.
Most annoying. fixed.
