### ISSUE TITLE
BUG: Promote does not promote

### ISSUE THREAD

**Issue by tucotuco** [VertNet/georefcalculator#75]
Select Calculation Type "Coordinates Only"
Select Location Type "Distance along orthogonal directions"
Select Coordinate System "degrees minutes seconds"
Select Latitude 35d 22m 30s N
Select Longitude 119d 0m 0s W
Select Datum NAD27
Select NS Offset distance 0.11498 S
Select EW Offset distance 1.00379 W
Select Distance Units "mi"

Click Calculate

Expected: Decimal Latitude 35.3733321 Decimal Longitude -119.0177772
Observed: Decimal Latitude 35.3733321 Decimal Longitude -119.0177772

So far, so good.

Click Promote

Expected: Latitude 35d 22m 24s N Longitude 119d 1m 4s W
Observed: No change in Latitude (35d 22m 30s N) and Longitude (119d 0m 0s W)

**Comment by ElSkunkito** [comment]
no longer repros, probably as a result of commit 8b6c804..3f51ed7.
please independantly verify.

**Comment by tucotuco** [comment]
Verified to function as expected. Closing.
