### ISSUE TITLE
BUG: Clearing values in converters does not clear results in converters

### ISSUE THREAD

**Issue by tucotuco** [VertNet/georefcalculator#76]
Enter 10 in Distance converter text box
Select "mi" in from units
Select "km" in to units

Expected: 16.09344 in results
Observed: 16.09344 in results

So far, so good.

Now, clear 10 from Distance converter text box

Expected: clear results
Observed: no change in results (remains 16.09344)

Similarly for Scale converter.

**Comment by ElSkunkito** [comment]
Fixed in commit 3f51ed7..57bb889
