### ISSUE TITLE
ENHANCEMENT: for the lazy, auto select all text on entry for all fields

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#77]
lets say I do calculation type 1.
for text fields where no value has been entered, i believe even hidden ones, 0 is
auto entered, no so important to the story, but relavent

now lets say i do a calculation type 2.
calc type 2 has different visible text fields and numbedrs because its vastly different than first calc

i tab though and adjust text fields as needed.

but for any text field I want to change completely, say
-123.45
and
0
to
34,7
and
89.345

I have to
DEL+DEL+DEL+DEL+DEL+DEL+DEL then NUMBERS
and 
DEL then NUMBERS 
or SHIFT+END+DEL then NUMBERS

too much damn work.

I would be nice upon text filed entry if all text was selected, than I either I could either
END/HOME + edits if the number is close
or more likelyNUMBERS right over top the selected text.

less keys = lazier = better

**Comment by tucotuco** [comment]
Full selection is already the behavior on Chrome MacOSX as of commit 03a7b178150ba55aeb5fa06c6486869206c0dd5e.

**Comment by ElSkunkito** [comment]
same for windows.

either I wasd confused when I filed it, thinking mouse click instead of 'getf focus'.

or yo0u fixed it.

either way -> closing.
