### ISSUE TITLE
BUG: default E/W is E

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#78]
I am unsure if other controls are affected.

repro
Calc: Error Only
Loc: Distance Only
Coord Sys: DMS

Expected
   Longitude ChoiceLongDirDMS is set to "W"

Actual:
   Longitude ChoiceLongDirDMS is set to "E"

**Comment by ElSkunkito** [comment]
marked high pri as I don't think this is every control, leading to habit trail mis calcs in actual user work.

**Comment by ElSkunkito** [comment]
This is a non bug, by design.
Longitude of 0 is E by default in JS and Java. I think in science as well.
Assigning JRW for confirmation on the science part and for him to close if so..

**Comment by tucotuco** [comment]
All good here. Closing.
