### ISSUE TITLE
Possible error in Promote

### ISSUE THREAD

**Issue by ElSkunkito** [VertNet/georefcalculator#82]
I do not know the science behind this but something is off

repro steps:
  calc:     error only
  loc:          dist at heading
  coord source: gazetteer
  coord system: DMS
  Lat:          12o 11' 12" N
  Long:     11o 12' 56" E

   Click Calculate
   Click Promote

Actual:
  Lat:          12o 11' 12" N
  Long:     11o 13' -4" E

Expected, Unknown to me
   I find the -4 very suspicious as the allowed range is 0-60
   Maybe it should be
       Long:        11o 12' 56" E
    as before

Continuing
   Click Calculate

Actual
    Error dialog "-4 is not in the allowed range of 0-60"

Expected
   No error dialog

using a local version of the java App has my expected values for Long

**Comment by ElSkunkito** [comment]
please advise

**Comment by ElSkunkito** [comment]
Max error differs, hmm.

_Calc Full Result for JS_
12.1866667  11.2155556  _206180_    datum not recorded  degrees minutes seconds 0   206.18  km  100 km  nearest degree

_Calc Full Result for Java_
12.1866667  11.2155556  _156680_    datum not recorded  degrees minutes seconds 0

**Comment by tucotuco** [comment]
This b2bd4bfcca9347797f0f259d59b145010cb86ae7 should have fixed the '4 seconds. Did you git pull origin master before trying?  Will check error calc.

**Comment by ElSkunkito** [comment]
This no longer repros.
based on date of filing the bug I did not yet have the fix.

Also I had slightly different settings for JAVA and JS Distance Precision which accounted for the
Max Error difference.

Apologies.

Closing.

**Comment by ElSkunkito** [comment]
The issue is a non issue, see comments.
