### ISSUE TITLE
Deprecate old documentation

### ISSUE THREAD

**Issue by pzermoglio** [VertNet/georefcalculator#95]
Old documentation for the calculator is accessible here:
Wieczorek J & Bloom DA. 2015. Manual for the Georeferencing Calculator. University of California, Berkeley: Museum of Vertebrate Zoology. [http://georeferencing.org/gci2/docs/GeoreferencingCalculatorManualv2.html ](http://georeferencing.org/gci2/docs/GeoreferencingCalculatorManualv2.html )

That document should include at the very top some indicator that it is not the most current document, and that it has been superseded by:
Bloom DA, Wieczorek JR, Zermoglio PF. 2020. Georeferencing Calculator Manual. Copenhagen: GBIF Secretariat. [https://doi.org/10.35035/gdwq-3v93](https://doi.org/10.35035/gdwq-3v93) 
[note that doi does not resolve yet, but it will]

**Comment by tucotuco** [comment]
Done. Thank you.
